version: "3.9"
services:
  postgres:
    build:
      context: ./postgres-dev
    environment:
      POSTGRES_DB: BlackExoticsDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    expose:
      - 5433

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: blackexotics
    ports:
      - "5050:80"